name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build SingleLinkedList
        run: |
          cd SingleLinkedList
          cargo build --verbose

      - name: Test SingleLinkedList
        run: |
          cd SingleLinkedList
          cargo test --verbose

      - name: Build DoubleLinkedList
        run: |
          cd DoubleLinkedList
          cargo build --verbose

      - name: Test DoubleLinkedList
        run: |
          cd DoubleLinkedList
          cargo test --verbose
